# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Lilly 
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Lilly is a musician and audio engineer turned computer science student, interested in Machine Intelligence and Ethical AI.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mobillombokmurah.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  mobillombokmurah

destination: "./docs"

# Build settings
#remote_theme: erlzhang/jekyll-theme-persephone
theme: jekyll-theme-persephone
plugins:
  - jekyll-books
  - jekyll-feed


# Theme Settings
logo: /img/logo.png
rss: "/feed.xml"
theme: 'jekyll-theme-persephone'
theme_setting:
  blog_page: "blog/index.md"
  about_page: "about.md"
  archive_page: "archive.md"
  nav_pages:
    - "about.md"
    - "archive.md"
  lang:
    category_all: "全部"
    blog_title: "博客"
    comment:
      user: "昵称"
      email: "邮箱"
      url: "链接"
      message: "说点什么吧..."
      reply: "回复"
comment:
  enabled: true
  provider: "static"
  static:
    postUrl: "https://jekyll-comment-server.herokuapp.com/post-comment"
    # postUrl: "https://g4vdkkahpjie.leanapp.cn/post-comment"
smiley:
  enabled: true
head_code: |
  <script>
    var _hmt = _hmt || [];
    (function() {
      var hm = document.createElement("script");
      hm.src = "https://hm.baidu.com/hm.js?3176e6e675ed7773f831e38c7a57880f";
      var s = document.getElementsByTagName("script")[0]; 
      s.parentNode.insertBefore(hm, s);
    })();
  </script>

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key heråe will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
